# Site settings
title: TechBrief
email: hiattp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on ruby, rails, testing, vim, technology products
  and product development, with the occasional hardware/software hack thrown in
  for good measure.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.paulrugelhiatt.com" # the base hostname & protocol for your site
# url: "http://localhost:4000"
github_username:  hiattp

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
