# Site settings
title: TechBrief
email: hiattp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on web technologies and product development, with an
  emphasis on brevity.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.paulrugelhiatt.com" # the base hostname & protocol for your site
github_username:  hiattp

# Build settings
markdown: kramdown
